# Generated by Django 5.0.2 on 2024-03-01 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ccgc", "0002_alter_csvfile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="csvfile",
            name="file",
            field=models.FileField(upload_to=""),
        ),
    ]
